remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Loans - Loan Calculator Privacy & Support]
description: [Thank you for downloading Loans - Loan Calculator. This site is here to support any issues or help you need with the app.]